name: kaptured
favicon: null
layout_spectrum: 0.31358870421536267
typography_spectrum: 0.3222979048732668
title: journal of light
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2d9de'
    - '#292148'
    - '#90a6b1'
    - '#6f8ca0'
    - '#3a474a'
  brandStrength: 0.1875
  lightness: 0.8443195261061192
  saturation: 0.125
  rhythmicContrast: 0.6247322158887982
purpose: []
